#!/usr/bin/env bash
#displays 1-100
#fizz if multuple of 3
#buzz if multiple of 5
i=1
while [ $i -ne 101 ]
do
	if ((i%3 == 0)) && ((i%5 == 0))
	then
		echo "FizzBuzz"
	elif ((i%3 == 0))
	then
		echo "Fizz"
	elif ((i%5 == 0))
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
